[project]
name = "pxbadge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.124.4",
    "pillow>=12.0.0",
    "uvicorn>=0.30.0",
]
